#!/usr/bin/python

#p2gui

import wx
try:
    from agw import aui
except ImportError: # if it's not there locally, try the wxPython lib.
    import wx.lib.agw.aui as aui
import matplotlib
matplotlib.use('WXAgg')
from matplotlib.figure import Figure
from matplotlib.backends.backend_wxagg import \
    FigureCanvasWxAgg as FigCanvas, \
    NavigationToolbar2WxAgg as NavigationToolbar
from wx.lib.pubsub import Publisher
import core.tools.p2acnet as p2acnet
import threading
import numpy as np
import matplotlib.pyplot as plt
import matplotlib.dates as mdates
import time
from collections import defaultdict
import datetime as dt

# PubSub message classification
MSG_NOTIFY_ROOT = ('root',)

class Notifier(object):
    def __init__(self):
        super(Notifier, self).__init__()
        self._data = dict()

    def SetValue(self, key, value):
        self._data[key] = value
        # Notify all observers of config change
        Publisher.sendMessage(MSG_NOTIFY_ROOT + (key,), value)

    def GetValue(self, key):
        return self._data.get(key, None)

# Define notification event for thread completion
EVT_RESULT_ID = wx.NewId()
 
def EVT_RESULT(win, func):
    """Define Result Event."""
    win.Connect(-1, -1, EVT_RESULT_ID, func)
 
class ResultEvent(wx.PyEvent):
    """Simple event to carry arbitrary result data."""
    def __init__(self, data):
        """Init Result Event."""
        wx.PyEvent.__init__(self)
        self.SetEventType(EVT_RESULT_ID)
        self.data = data

#------------------Begin Main GUI Classes---------------------#

class ControlPanel(wx.Panel):
    def __init__(self, *args, **kwargs):
        super(ControlPanel, self).__init__(*args, **kwargs)
        self.channels = ['T-IFO', 'L-IFO', 'Outside Temp']
        self.start_times = ['Last Week', 'Yesterday']
        self.end_times = ['Now']
        self.createControls()
        self.bindEvents()
        self.doLayout()

        # Create dictionary of dictionaries for holding form data
        self.panel_dict = defaultdict(int)
        self.form_dict = {'Active_Tab_ID': '', 'Active_Tab_Label': '', \
                              'Title': '', 'Verbose': '', 'Grid': '', 'Channels': '',\
                              'Start_Time': '', 'End_Time': ''}

        # Create other state variables
        self.current_active_tab = None
        
        Publisher.subscribe(self.updateDisplay, MSG_NOTIFY_ROOT)        

    def createControls(self):
        self.activetabLabel = wx.StaticText(self, label="Active Tab:")
        self.activetabCtrl = wx.StaticText(self, label="Not Sure")
        self.runButton = wx.Button(self, label="Run")
        self.titleLabel = wx.StaticText(self, label="Title:")
        self.titleTextCtrl = wx.TextCtrl(self, value="Enter plot title here")
        self.channelLabel = wx.StaticText(self,
            label="Channels:")
        self.channelComboBox = wx.ComboBox(self, choices=self.channels,
            style=wx.CB_DROPDOWN, value="T-IFO")
        self.starttimeLabel = wx.StaticText(self, label="Start Time:")
        self.starttimeComboBox = wx.ComboBox(self, choices=self.start_times,
            style=wx.CB_DROPDOWN, value="Yesterday")
        self.endtimeLabel = wx.StaticText(self, label="End Time:")
        self.endtimeComboBox = wx.ComboBox(self, choices=self.end_times,
            style=wx.CB_DROPDOWN, value="Now")
        self.verboseCheckBox = wx.CheckBox(self, label="Do you want verbose output?")
        self.verboseCheckBox.SetValue(True)
        self.gridCheckBox = wx.CheckBox(self, label="Show Grid?")
        self.gridCheckBox.SetValue(False)
        
        # Create a Container for use with storing controls
        self.field_container = [self.activetabCtrl, self.titleTextCtrl, \
                                    self.channelComboBox, self.starttimeComboBox, \
                                    self.endtimeComboBox, self.verboseCheckBox, \
                                    self.gridCheckBox]

    def doLayout(self):
        # A GridSizer will contain the controls:
        gridSizer = wx.FlexGridSizer(rows=13, cols=2, vgap=10, hgap=10)

        # Prepare some reusable arguments for calling sizer.Add():
        expandOption = dict(flag=wx.EXPAND)
        noOptions = dict()
        emptySpace = ((0, 0), noOptions)

        # Active tab gets its own sizer
        tab_sizer = wx.BoxSizer(wx.HORIZONTAL)
        tab_sizer.Add(self.activetabLabel)
        tab_sizer.AddSpacer((5, 0))
        tab_sizer.Add(self.activetabCtrl)

        # Add the controls to the sizers:
        for control, options in \
                [emptySpace,
                 emptySpace,
                 (tab_sizer, expandOption),
                 emptySpace, 
                 (self.titleLabel, expandOption),
                 emptySpace,
                 (self.titleTextCtrl, expandOption),
                 emptySpace,
                 (self.channelLabel, noOptions),
                 emptySpace,
                 (self.channelComboBox, expandOption),
                  emptySpace,
                 (self.starttimeLabel, noOptions),
                 emptySpace,
                 (self.starttimeComboBox, expandOption),
                 emptySpace,
                 (self.endtimeLabel, noOptions),
                 emptySpace,
                 (self.endtimeComboBox, expandOption),
                 emptySpace,
                 (self.verboseCheckBox, noOptions),
                 emptySpace,
                 (self.gridCheckBox, noOptions),
                 emptySpace,
                 (self.runButton, dict(flag=wx.ALIGN_CENTER))]:
            gridSizer.Add(control, **options)
        # Finally, add a horizontal sizer to give extra space
        hsizer = wx.BoxSizer(wx.HORIZONTAL)
        hsizer.AddSpacer((10, 0))
        hsizer.Add(gridSizer)
            
        self.SetSizer(hsizer)

    def bindEvents(self):
        # Written this way to make it easy to add more bindings
        for control, event, handler in \
            [(self.runButton, wx.EVT_BUTTON, self.onRun)]:
            control.Bind(event, handler)

    def get_form_content(self):
        for form_element in self.field_container:
            if type(form_element) is wx._controls.StaticText:
                self.form_dict[form_element] = form_element.GetLabel()
            else:
                self.form_dict[form_element] = form_element.GetValue()

    def get_panel_label(self):
        self.form_dict[self.activetabCtrl] = self.activetabCtrl.GetLabel()

    def onRun(self, event):
        """
        Runs the thread, sending the query to acnet and reporting the results
        to the mplpanel via the custom event ResultEvent
        """
        Title = self.titleTextCtrl.GetValue()
        if Title == 'Enter plot title here':
            Title = ''
        Channel = str(self.channelComboBox.GetValue())
        if Channel == 'T-IFO':
            Channel_list = ['E:TCIP', 'E:TNIP0', 'E:TNIP1', 'E:TNESIP', 'E:TEIP0',\
                                'E:TEIP1', 'E:TEESIP']
        elif Channel == 'L-IFO':
            Channel_list = ['E:LCIP', 'E:LNIP0', 'E:LNIP1', 'E:LNESIP', 'E:LEIP0',\
                                'E:LEIP1', 'E:LEESIP']
        elif Channel == 'Test':
            Channel_list = ['G:OUTTMP', 'E:TCIP']
        else:
            Channel_list = Channel.split(', ')
        Start_time = str(self.starttimeComboBox.GetValue())
        if Start_time == 'Last Week':
            Start_time = 'Last_Week'
            start_fmt = self.get_date(7)
        elif Start_time == 'Yesterday':
            start_fmt = self.get_date(1)
        else:
            start_fmt = Start_time
        End_time = str(self.endtimeComboBox.GetValue())
        if End_time == 'Now':
            end_fmt = self.get_date()
        else:
            end_fmt = End_time
        Verbose = self.verboseCheckBox.GetValue()
        Grid = self.gridCheckBox.GetValue()
        mplcanvas_msg_dict = dict([('title', Title), ('start', start_fmt), \
                                      ('end', end_fmt), ('grid', Grid)])
        wx.PostEvent(self, ResultEvent(['mpl_canvas', mplcanvas_msg_dict]))
        def innerrun():
            query = p2acnet.P2ACNET(Channel_list, Start_time, End_time, \
                                        verbose=Verbose, \
                                        print_method=self.printLogger\
                                        )
            info_dict = query.get_group_info()
            wx.PostEvent(self, ResultEvent(['mpl_canvas_info_dict', info_dict]))
            data = query.get_group_data()
            wx.PostEvent(self, ResultEvent(['plot_data', data]))
        Query = threading.Thread(target=innerrun)
        Query.start()
        self.runButton.Disable()
        self.printLogger('Query Started')
    
    def get_date(self, days='Today'):
        '''
        This method returns today's date/time formatted according to the ACNET time
        query standard. This helps in plot labeling.
        '''
        today = dt.datetime.today()
        if days == 'Today':
            date_fmt = today.strftime("%d-%b-%Y-%H:%M")
        else:
            interval = dt.timedelta(days)
            date_raw = today - interval
            date_fmt = date_raw.strftime("%d-%b-%Y-%H:%M")
        return date_fmt

    def printLogger(self, msg):
        wx.PostEvent(self, ResultEvent(['logger', msg+'\n']))
        
    def updateDisplay(self, msg):
        if msg.topic[-1] == 'control':
            if msg.data in 'update button':
                self.runButton.Enable()
        if msg.topic[-1] == 'nb_panel_changed':
            print "nb_panel_change event"
            if len(self.panel_dict) is not 0:
                if type(self.panel_dict[msg.data[0]]) is int:
                    self.activetabCtrl.SetLabel(msg.data[1])
                if type(self.panel_dict[msg.data[0]]) is not int:
                    self.retrieve_form_info(msg.data[0])
            else:
                self.activetabCtrl.SetLabel(msg.data[1])
            self.current_active_tab = msg.data[0]
            print "Current Active Tab ID:", self.current_active_tab
        if msg.topic[-1] == 'nb_panel_changing':
            print "nb_panel_changing event"
            self.store_fields(self.current_active_tab)

    def retrieve_panel_label(self, tab_data):
        print tab_data
        for (form_element, value) in self.panel_dict[tab_data[0]].items():
            form_element.SetLabel(tab_data[1])

    def retrieve_form_info(self, tab_index):
        for (form_element, value) in self.panel_dict[tab_index].items():
            # form_element.SetLabel(value)
            if isinstance(form_element, wx._controls.ComboBox):
                print "type Form_element", str(type(form_element))
                print "value", value
                form_element.SetValue(value)
            # if type(form_element) is wx._controls.CheckBox:
            #     form_element.SetValue(value)

    def store_fields(self, active_tab_index):
        # This will store the fields in a dictionary of dictionaries
        #   where the keys of the larger dictionaries are the notebook tab
        #   ID's and the values are the dictionaries of field:value pairs
        self.get_form_content()
        self.panel_dict[active_tab_index] = self.form_dict

class MPLPanel(wx.Panel):
    def __init__(self, *args, **kwargs):
        super(MPLPanel, self).__init__(*args, **kwargs)

        # Setup the canvas
        self.dpi = 100
        self.fig = Figure((4.0, 5.0), dpi=self.dpi)
        self.ax = None
        self.canvas = FigCanvas(self, -1, self.fig)
        self.ax_dict = None

        # Setup the toolbar
        self.toolbar = NavigationToolbar(self.canvas)
        self.toolbar.AddSeparator()
        self.statusctrl = wx.TextCtrl(self.toolbar, style=wx.TE_READONLY, \
                                          size=wx.Size(250,25))
        self.toolbar.AddControl(self.statusctrl)

        # Bind mouse events to mplcanvas
        # Note that event is a MplEvent
        self.canvas.mpl_connect('motion_notify_event', self.UpdateStatusBar)
        self.canvas.Bind(wx.EVT_ENTER_WINDOW, self.ChangeCursor)

        # Do the layout
        panelvbox = wx.BoxSizer(wx.VERTICAL)
        panelvbox.Add(self.canvas, 1, flag=wx.EXPAND|wx.GROW|wx.ALL)
        panelvbox.Add(self.toolbar, 0, wx.EXPAND)
        self.SetSizer(panelvbox)
        panelvbox.Fit(self)
        self.canvas.draw()

        # Observer of Notify events
        Publisher.subscribe(self.OnPlotUpdate, MSG_NOTIFY_ROOT)

    def UpdateStatusBar(self, event):
        """Function to update statusbar with mouse position"""
        if event.inaxes:
            x, y = event.xdata, event.ydata
            xformat = dt.datetime.strftime(mdates.num2date(x), '%d-%b-%Y-%H:%M')
            if np.log10(y) < -5:
                yformat = "%e" % y
            else:
                yformat = "%f" % y
            self.statusctrl.SetValue("x=" +xformat + " y=" +yformat)

    def ChangeCursor(self, event):
        self.canvas.SetCursor(wx.StockCursor(wx.CURSOR_BULLSEYE))

    def OnPlotUpdate(self, msg):
        if msg.topic[-1] == 'plot_data':
            if self.ax_dict != None:
                for i in self.ax_dict.keys():
                    self.ax_dict[i].clear()
                self.fig.clear()
            data_dict = msg.data
            #-----Decide how many subplots based on units-----#
            units_dict = defaultdict(list)
            for (channel, info_array) in self.info_dict.items():
                units_dict[info_array[1]].append(channel)
            num_units = len(units_dict)
            #------Try making a dictionary of axes instances--#
            self.ax_dict = {}
            #-----Make subplot for each unit------------------#
            for index, key in enumerate(units_dict):
                self.ax_dict[index] = self.fig.add_subplot(num_units, 1, index + 1)
                for channel in units_dict[key]:
                    data = data_dict[channel]
                    xdata = mdates.date2num(data[:,0])
                    ydata = data[:,1]
                    self.ax_dict[index].plot_date(xdata, ydata, '-', label=channel)
                    self.ax_dict[index].set_ylabel(key)
                if index == 0:
                    self.ax_dict[index].set_title(self.title)
                if 'TORR' in key:
                    self.ax_dict[index].set_yscale('log')
                self.ax_dict[index].legend(loc="best").get_frame().set_alpha(.5)
                if index == (num_units-1):
                    self.ax_dict[index].set_xlabel(str("T1 = "+ self.start+\
                                                           "      T2 = "+\
                                                           self.end))
                    self.ax_dict[index].grid(b=self.grid, which='both')
                    # Grid won't show without newest version of matplotlib
            self.fig.autofmt_xdate()
            self.canvas.draw()
            wx.PostEvent(self, ResultEvent(['control', 'update button']))
            wx.PostEvent(self, ResultEvent(['logger', 'Query Finished\n']))
        if msg.topic[-1] == 'mpl_canvas_info_dict':
            self.info_dict = msg.data
        if msg.topic[-1] == 'mpl_canvas':
            self.title = msg.data['title']
            self.start = msg.data['start']
            self.end = msg.data['end']
            self.grid = msg.data['grid']

class LoggerCtrl(wx.TextCtrl):
    def __init__(self, *args, **kwargs):
        super(LoggerCtrl, self).__init__(*args, **kwargs)
        # Observer of Notify events
        Publisher.subscribe(self.updateDisplay, MSG_NOTIFY_ROOT)

    def updateDisplay(self, msg):
        """
        Receives data from thread and updates the display
        """
        if 'logger' in msg.topic[-1]:
            t = msg.data
            self.AppendText(str(t))

MPLPanel_ID = wx.NewId()

class P2Frame(wx.Frame):
    def __init__(self, *args, **kwargs):
        super(P2Frame, self).__init__(*args, **kwargs)
        self._mgr = aui.AuiManager(self)
        mplpanel1 = MPLPanel(self, MPLPanel_ID)
        mplpanel2 = MPLPanel(self, MPLPanel_ID+1)
        self.auinb = aui.AuiNotebook(self)
        self.auinb.AddPage(mplpanel1, "Plot Canvas 1", select=True)
        self.auinb.AddPage(mplpanel2, "Plot Canvas 2")
        loggerctrl = LoggerCtrl(self, size=wx.Size(800, 100), \
                                    style=wx.TE_MULTILINE|wx.TE_READONLY)
        controlpanel = ControlPanel(self, size=wx.Size(250, 400))
        
        self._mgr.AddPane(controlpanel,\
                          aui.AuiPaneInfo().Caption('P2ACNET Controls').
                          Left().MinimizeButton(True))
        self._mgr.AddPane(self.auinb, aui.AuiPaneInfo().Caption('Plot Panel').
                          Center().MinimizeButton(True).MaximizeButton(True))
        self._mgr.AddPane(loggerctrl, aui.AuiPaneInfo().Caption('Notifications').
                          Bottom().MinimizeButton(True).MaximizeButton(True))
        self._mgr.Update()

        # Bind notebook panel change events
        self.Bind(aui.EVT_AUINOTEBOOK_PAGE_CHANGED, self.on_page_changed)
        self.Bind(aui.EVT_AUINOTEBOOK_PAGE_CHANGING, self.on_page_changing)
        
        # Send active panel info to control Panel
        active_tab_index = self.auinb.GetSelection()
        active_tab_info_list = [active_tab_index, \
                                    self.auinb.GetPageText(active_tab_index)]
        wx.PostEvent(self, ResultEvent(['nb_panel_changed',\
                                            active_tab_info_list]))
        
        # Observer of Notify Events
        # Publisher.subscribe(self.on_posted_event, MSG_NOTIFY_ROOT)
        
    def on_page_changed(self, event):
        active_tab_index = self.auinb.GetSelection()
        active_tab_label = self.auinb.GetPageText(active_tab_index)
        active_tab_info_list = [active_tab_index, active_tab_label]
        wx.PostEvent(self, ResultEvent(['nb_panel_changed',\
                                            active_tab_info_list]))
    
    def on_page_changing(self, event):
        # This is for notifying the control panel that the active tab
        #  will be changing, so it should record its fields

        active_tab_index = self.auinb.GetSelection()
        active_tab_label = self.auinb.GetPageText(active_tab_index)
        active_tab_info_list = [active_tab_index, active_tab_label]
        wx.PostEvent(self, ResultEvent(['nb_panel_changing',\
                                            active_tab_info_list]))



class P2App(wx.App):
    def OnInit(self):
        self.frame = P2Frame(None, title="P2ACNET GUI", size=(1000, 700))
        self.frame.Show(True)
        # Initialize the notification system
        self.notify = Notifier()
        # Make the app the subscriber to our made up ResultEvents
        EVT_RESULT(self, self.ReportNotifier)
        return True                    

    def GetNotify(self):
        return self.notify

    def ReportNotifier(self, notifydict):
        '''
        @param: notifydata is a dictionary, where each key
        is a differnt subscriber of the notification system
        to send its value (the data) to 
        '''
        data = notifydict.data
        if type(data) == dict:
            for key in data.keys():
                self.notify.SetValue(key, data[key])
        else:
            self.notify.SetValue(data[0], data[1])
        return


if __name__ == '__main__':
    app = P2App()
    app.MainLoop()


